In [55]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
# fix random seed for reproducibility
np.random.seed(2)

In [78]:
#load dataset
dataset = np.loadtxt("sockTrainingYesNo.csv", delimiter=",")
datasetTest = np.loadtxt("sockTest.csv", delimiter=",")
#Split data set into input (X) and output (Y) variables
X = dataset[:,0:LAYERS[0]]
Y = dataset[:,LAYERS[0]: LAYERS[0]+6]

Xtest = datasetTest[:,0:LAYERS[0]]
Ytest = datasetTest[:,LAYERS[0]: LAYERS[0]+6]

print ('Training x is', X)
print ('Training y is ', Y)
print ('Test x is', Xtest)
print ('Test y is', Ytest)

Training x is [[ 0.7964  0.6761  0.6992  0.8741  0.3455]
 [ 0.6503  0.5877  0.4835  0.5395  0.315 ]
 [ 0.6673  0.6899  0.3504  0.5829  0.3297]
 [ 0.8762  0.4485  0.3402  0.3451  0.2119]
 [ 0.7865  0.6839  0.7074  0.3937  0.2277]
 [ 0.5125  0.4522  0.05    0.1515  0.6633]]
Training y is  [[ 0.  0.  1.  1.  0.  1.]
 [ 1.  0.  1.  1.  0.  0.]
 [ 1.  0.  1.  1.  1.  0.]
 [ 1.  0.  1.  0.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.]
 [ 1.  0.  1.  1.  0.  0.]]
Test x is [[ 0.7964  0.6761  0.6992  0.8741  0.3455]
 [ 0.6503  0.5877  0.4835  0.5395  0.315 ]
 [ 0.6673  0.6899  0.3504  0.5829  0.3297]
 [ 0.8762  0.4485  0.3402  0.3451  0.2119]
 [ 0.7865  0.6839  0.7074  0.3937  0.2277]
 [ 0.5125  0.4522  0.05    0.1515  0.6633]]
Test y is [[ 0.  0.  1.  1.  0.  1.]
 [ 1.  0.  1.  1.  0.  0.]
 [ 1.  0.  1.  1.  1.  0.]
 [ 1.  0.  1.  0.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.]
 [ 1.  0.  1.  1.  0.  0.]]


In [79]:
#DEFINE THE MODEL - SEQUENCE OF LAYERS
#Create a sequential model and add layer one at a time
#Until we are happy with network topology

#Layers
LAYERS = [5, 16, 6]

#Create a Model
model = Sequential()
model.add(Dense(LAYERS[0],input_dim=LAYERS[0], activation='relu'))
model.add(Dense(LAYERS[1], activation='relu'))
model.add(Dense(LAYERS[2], activation = 'sigmoid'))
# model.add(Activation('softmax'))

#Compile the Model
model.compile(loss='binary_crossentropy', optimizer="adam", metrics=['accuracy'])

In [89]:
#Fit the Model
#we can train or fit the model on loaded data by calling the fit() function on the model
#Training process runs for fixed # iterations throu ght data called
#epochs. We need to specify this  in nepochs

model.fit(X,Y, epochs=100,batch_size=5)

#EVALUATE THE MODEL
#now that we have trained it on training data, evaluate performance on same dataset
#Lets us know how well we modeled the dataset, but not
#How it will perform on new data

scores = model.evaluate(X,Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/100
6/6 [==============================] - 0s - loss: 0.3279 - acc: 0.8333     
Epoch 2/100
6/6 [==============================] - 0s - loss: 0.3275 - acc: 0.8333     
Epoch 3/100
6/6 [==============================] - 0s - loss: 0.3271 - acc: 0.8333     
Epoch 4/100
6/6 [==============================] - 0s - loss: 0.3272 - acc: 0.8333     
Epoch 5/100
6/6 [==============================] - 0s - loss: 0.3268 - acc: 0.8333     
Epoch 6/100
6/6 [==============================] - 0s - loss: 0.3268 - acc: 0.8333     
Epoch 7/100
6/6 [==============================] - 0s - loss: 0.3263 - acc: 0.8333     
Epoch 8/100
6/6 [==============================] - 0s - loss: 0.3260 - acc: 0.8333     
Epoch 9/100
6/6 [==============================] - 0s - loss: 0.3259 - acc: 0.8333     
Epoch 10/100
6/6 [==============================] - 0s - loss: 0.3258 - acc: 0.8333     
Epoch 11/100
6/6 [==============================] - 0s - loss: 0.3255 - acc: 0.8333     
Epoch 12/100
6/6 [============

6/6 [==============================] - 0s - loss: 0.3091 - acc: 0.8611     
Epoch 92/100
6/6 [==============================] - 0s - loss: 0.3086 - acc: 0.8611     
Epoch 93/100
6/6 [==============================] - 0s - loss: 0.3083 - acc: 0.8611     
Epoch 94/100
6/6 [==============================] - 0s - loss: 0.3080 - acc: 0.8611     
Epoch 95/100
6/6 [==============================] - 0s - loss: 0.3077 - acc: 0.8611     
Epoch 96/100
6/6 [==============================] - 0s - loss: 0.3075 - acc: 0.8611     
Epoch 97/100
6/6 [==============================] - 0s - loss: 0.3072 - acc: 0.8889     
Epoch 98/100
6/6 [==============================] - 0s - loss: 0.3074 - acc: 0.8889     
Epoch 99/100
6/6 [==============================] - 0s - loss: 0.3073 - acc: 0.8611     
Epoch 100/100
6/6 [==============================] - 0s

acc: 86.11%


In [90]:
#TIE IT ALL TOGETHER - PREDICT SOMETHING!!!!

predictions=model.predict(Xtest)

#round the predictions
rounded = [round(x[0], 1) for x in predictions]
print ("The answer is ", rounded)
print("predictions are", predictions)

for n in predictions:
    favSock = max(n)
    favSockI = np.argmax(n)
    print ("fav sock is", favSock)
    print ("index of fav sock is", favSockI )
   


The answer is  [0.5, 0.60000002, 0.80000001, 0.69999999, 0.2, 1.0]
predictions are [[  4.72994626e-01   1.23664795e-04   8.65882456e-01   9.19237256e-01
    5.78211844e-01   6.85910821e-01]
 [  6.41631067e-01   7.65168341e-04   9.07206595e-01   8.69007170e-01
    5.05423486e-01   5.38227856e-01]
 [  7.70255685e-01   9.23454179e-04   9.64020669e-01   8.81092548e-01
    4.16524321e-01   4.21913534e-01]
 [  7.18474984e-01   1.41197920e-03   8.93387258e-01   7.90408909e-01
    5.09266555e-01   5.27430058e-01]
 [  1.96056828e-01   3.02237459e-04   3.14982951e-01   8.44296694e-01
    7.58257926e-01   8.38626683e-01]
 [  9.87665176e-01   1.10966796e-02   9.99337852e-01   8.34332764e-01
    1.32720247e-01   6.19125739e-02]]
fav sock is 0.919237
index of fav sock is 3
fav sock is 0.907207
index of fav sock is 2
fav sock is 0.964021
index of fav sock is 2
fav sock is 0.893387
index of fav sock is 2
fav sock is 0.844297
index of fav sock is 3
fav sock is 0.999338
index of fav sock is 2
